services:
  - type: web
    name: photo-bot
    env: python
    region: frankfurt # или ближайший регион
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
